name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest -v test_app.py
    
    - name: Build Docker image
      run: docker build -t my-flask-app .
    
    - name: Run container test
      run: |
        docker run -d -p 5000:5000 --name test-app my-flask-app
        sleep 5
        curl http://localhost:5000
